version: '3.1'
services:
  msa-mysql:
    container_name: msa-mysql80
    image: mysql/mysql-server:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ROOT_HOST=%
      - TZ=Asia/Seoul
    command: [ "--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci", "--lower_case_table_names=1" ]
    ports:
      - "13306:3306"
    volumes:
      - ./mysql-init.d:/docker-entrypoint-initdb.d
  msa-adminer: # mysql web admin
    container_name: msa-adminer
    image: adminer:4
    ports:
      - "18080:8080"
    environment:
      - ADMINER_DEFAULT_SERVER=msa-mysql80
      - ADMINER_DESIGN=nette
      - ADMINER_PLUGINS=tables-filter tinymce

